---
# Install and configure OpenSSH server and client

- include_vars: "{{ ansible_distribution }}.yml"

## Install ssh packages
- name: install ssh packages
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pkgs }}"

- name: Load OpenSSH version
  shell: "ssh -V 2>&1 | sed -E 's/([a-zA-Z_]+)([0-9.]+)(.*)/\\2/g'"
  register: sshv
  changed_when: False

## Manage host configuration
- name: copy host configuration
  become: True
  template:
    src: etc_ssh_sshd__config.j2
    dest: /etc/ssh/sshd_config
    validate: 'sshd -T -f %s'
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
  register: result

## Manage client configuration
- name: copy client configuration
  become: True
  template:
    src: etc_ssh_ssh__config.j2
    dest: /etc/ssh/ssh_config
    owner: root
    group: root
    mode: 0644

## Manage authorized_keys
- name: add authorized keys
  become: True
  authorized_key:
    user: "root"
    key: "{{ lookup('file', ssh_user_key_loc + '/' + item + '.pub') }}"
  with_items: "{{ ssh_authorized_keys }}"
  when: ssh_deploy_root_authorized_keys

- meta: flush_handlers
